### ISSUE TITLE
Workaround for loading hparams without tf 1.x ? 

### ISSUE THREAD

**Issue by turian** [Rayhane-mamah/Efficient-VDVAE#7]
Colab no longer supports tensorflow 1.x

Is there a workaround for loading the hparams cfg? 

I tried hparams pypi package but it didn't work.

Also the following didn't work:
```
# https://github.com/tensorflow/community/issues/148
from tensorboard.plugins.hparams import api as hp
hparams = hp.HParams('.', name="efficient_vdvae")


```

**Comment by Rayhane-mamah** [comment]
Hello @turian and thank you for the interest in our work.

As explained in the README, the hparams we use isn't the tensorflow hparams module, but a similar behaving one.

The package isn't hosted on pypi yet and can be installed with (confirmed it works on colab):

```
pip install --upgrade git+https://github.com/Rayhane-mamah/hparams
```

Basic usage can be found [here](https://github.com/Rayhane-mamah/hparams) if you are writing your own code.

Let me know if this solves your problem.
